### PR TITLE
Refined Database Architecture and User Interaction

### PR DESCRIPTION
**Pull request by RageKage**
Refined Database and also creating another db for the aircraft and creating api calls to populate that db with the api data we want. create func's to preform CRUD on only the UserDB because the other DB can't be altered, also set up some valiadtions to make sure that db folder exists and also creating db and running the api to populate the db only once (this saves us api calls and also user time).

### CODE REVIEW

**Comment by ju957** [comment]
The functions themselves seem fine, however documentation should be improved, such as clarifying what each database is supposed to be used for and what functions are associated with each database, what an ICAO code is vs a model name, and a brief description for every important function in databaseManager.py.

Also the menu options should be renamed to not mention databases or APIs, since the average user won't know what those are. I suggest 'Bookmarked Plane Search' and 'Online Plane Search' for the first two options.

**Comment by RageKage** [comment]
> The functions themselves seem fine, however documentation should be improved, such as clarifying what each database is supposed to be used for and what functions are associated with each database, what an ICAO code is vs a model name, and a brief description for every important function in databaseManager.py.
> 
> Also the menu options should be renamed to not mention databases or APIs, since the average user won't know what those are. I suggest 'Bookmarked Plane Search' and 'Online Plane Search' for the first two options.

Okay, so add more docs to the db manager and then reorder the menu options? Can you tell me In like what order? 


also I’m not sure I follow what you meant by menu options shouldn’t be mentioning the database or api?

**Comment by RageKage** [comment]
> The functions themselves seem fine, however documentation should be improved, such as clarifying what each database is supposed to be used for and what functions are associated with each database, what an ICAO code is vs a model name, and a brief description for every important function in databaseManager.py.
> 
> Also the menu options should be renamed to not mention databases or APIs, since the average user won't know what those are. I suggest 'Bookmarked Plane Search' and 'Online Plane Search' for the first two options.

so I add more docs to the db manager and also I didn't realize this before but I updated the few variables both in the main and the db manager. The original names didn't made sense and confused me as well so I changed them for better readable to know what each func is going to do. I will keep in mind this next time.

**Review by ju957 — APPROVED** [review]
Looks much better. Thank you for for changing the database names.

**Pull request merged**
